### PR TITLE
Get peers from github ARK-Peers

### PR DESCRIPTION
**Pull request by air1one**
For issue #46 .

I used await to make the request to github so I had to put everything inside an anonymous async function.

### CODE REVIEW

**Comment by faustbrian** [comment]
I think this is better to be implemented in https://github.com/ArkEcosystem/ark-client/tree/develop for the next version.

@wownmedia Have you already thought about where you would put the peer loading?

**Comment by faustbrian** [comment]
Stupid me, this was already implemented in the latest PR of @wownmedia as he copied over my code from ARK-JSON-RPC.

https://github.com/ArkEcosystem/ark-client/blob/develop/lib/services/network.js#L141-L147

**Comment by CryptologySAC** [comment]
Yes, in my opinion /lib/config/networks.js. For now I followed what you did with the RPC and used the same file as in ARK-JSON-RPC, then when V2 is released we can see how and what to implement in case anything changes. @air1one would that work for you too?

**Comment by air1one** [comment]
OK my bad didn't checked the *develop* branch. I'm good with @wownmedia PR 👍

**Pull request closed without merging**
