### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by boveus**
This corrects the PR template.  Please see https://github.com/ArkEcosystem/javascript-cli/issues/112 for more details.

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Comment by ghost** [comment]
The [ci/circleci: test-node-9](https://circleci.com/gh/ArkEcosystem/javascript-cli/20?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [3748cf538750f849a552d630bb611465de6b645b](https://github.com/ArkEcosystem/javascript-cli/commit/3748cf538750f849a552d630bb611465de6b645b). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/javascript-cli/20?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ghost** [comment]
The [ci/circleci: test-node-9](https://circleci.com/gh/ArkEcosystem/javascript-cli/20?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [3748cf538750f849a552d630bb611465de6b645b](https://github.com/ArkEcosystem/javascript-cli/commit/3748cf538750f849a552d630bb611465de6b645b). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/javascript-cli/20?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 6. _It will earn you $1 USD._

**Pull request merged**
