### PR TITLE
Fix for displaying wallet balance + sending ark amount

### PR DESCRIPTION
**Pull request by roks0n**
### Current state:
**Failed to send 0.48086401 dark:**
```
ark devnet> account send 0.48086401 DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR
passphrase: ****************************************************************************
? Sending 0.48086401DARK to DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR now Yes
Failed to send transaction: Failed to validate transaction schema: Expected type integer but found type number
```

**Sending 1 dark actually sends 0.00000001 dark:**
If sending in USD it sends the correct amount of dark.
```
ark devnet> account send 1 DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR
passphrase: ****************************************************************************
? Sending 1DARK to DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR now Yes
Transaction sent successfully with id e82d196bb39e4a5a2fdb87cf1fe9ece5a6776ab99446e2fc8dd53ac28752d0d6
```
Tx: https://dexplorer.ark.io/transaction/e82d196bb39e4a5a2fdb87cf1fe9ece5a6776ab99446e2fc8dd53ac28752d0d6

**Account status not showing correct balance**
```
ark devnet> account status DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR
.-------------------------------------------------------------------------------------------------------.
| unconfirmedBalance |   balance   |                             publicKey                              |
|--------------------|-------------|--------------------------------------------------------------------|
| 96109999989        | 96109999989 | 033716320f2fcc0c29a2b8c76b3aabb34516a3aad226fb97ef4a55dee1f2dc3077 |
'-------------------------------------------------------------------------------------------------------'
```

### Fixed version:

```
ark devnet> account send 0.48086401 DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR
passphrase: ****************************************************************************
? Sending 0.48086401 DARK to DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR now Yes
Transaction sent successfully with id becc30515e13e25cc5dd336b44790863307f17cee428c00d5ead6f77c55227e1
```
TX: https://dexplorer.ark.io/transaction/becc30515e13e25cc5dd336b44790863307f17cee428c00d5ead6f77c55227e1

```
ark devnet> account status DMsYKeSJKk5AdUZNK6ztRPc68kQozCNdUR
.--------------------------------------------------------------------------------------------------------.
| unconfirmedBalance |   balance    |                             publicKey                              |
|--------------------|--------------|--------------------------------------------------------------------|
|       961.09999989 | 961.09999989 | 033716320f2fcc0c29a2b8c76b3aabb34516a3aad226fb97ef4a55dee1f2dc3077 |
'--------------------------------------------------------------------------------------------------------'
```

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Looks good to me. All working as expected 👍 although i think sending "1" dark, should actually send 1, not 0.00000001. Specifying "1.0" works, however.

**Comment by alexbarnsley** [comment]
Nice work by the way 👍

**Comment by roks0n** [comment]
I don't remember now, but I think this fix should send 1 dark when specifying 1. 🤔 That example "Sending 1 dark actually sends 0.00000001 dark:" was to show how it worked before this fix.

Ty Alex!

**Comment by alexbarnsley** [comment]
Apologies, my "1" was sent when testing before your change. Happy this is working as you wanted it 👍

**Pull request merged**
