### PR TITLE
Fixed Code Intendation

### PR DESCRIPTION
**Pull request by kalgoop**
Corrected JS code Indentation according to the conventions used in ARK repo

### CODE REVIEW

**Comment by alexbarnsley** [comment]
thanks! 👍

**Comment by boldninja** [comment]
Hi @kalgoop can you please provide me your ARK address or contact me on ARK's Slack (username : boldninja)?

**Comment by kalgoop** [comment]
AHTUWv2BqS78ZuTKu5aHL8bQX3VjoXxRik

**Comment by boldninja** [comment]
Sent @kalgoop

**Pull request merged**
